
# User theme customization (optional; via custom files)
# * (modified from the ['NexT' hexo theme](https://github.com/theme-next/hexo-theme-next))
# * define custom file paths
# * eg, you want to put your custom styles file outside theme directory, in <root> `source/_data`, set `styles: source/_data/styles.styl`; use <root> relative paths
custom_file_path:
  # # Default paths: layout/_custom/*
  # head: source/_data/head.swig
  # header: source/_data/header.swig
  # sidebar: source/_data/sidebar.swig
  variables: null   # default path: <theme>/source/css/_variables/custom.styl
  mixins: null  # default path: <theme>/source/css/_mixins/custom.styl
  styles: null  # default path: <theme>/source/css/_styles/custom.styl

# Page language (html attribute)
language: en

# Main menu navigation items
menu:
  Blog: /
  Archives: /archives
  # Title: /pageName - create using `hexo new page 'pageName'`

# Post social sharing features
social:
  twitter: your_twitter # set to your twitter handle

# Page sidebars
# Components will appear in the order they are specified
sidebars:
  recent: true # boolean to display 10 most recent posts
  featured: false # boolean to list all posts with tag 'featured'
  github: your_github # string to point to a Github profile | false to disable
  collapsed: false # boolean to display sidebar as collapsed

# Disqus comments
disqus:
  enabled: false
  shortname: your_website_shortname

# Analytics
googleAnalytics: false # false | string (UA-xxxx ID)

# Link to atom.xml in nav bar?
# You can use https://github.com/hexojs/hexo-generator-feed to generate these
atom: true

# Stylesheets loaded in the <head>
stylesheets:

# Scripts loaded at the end of the body
scripts:

colors:
  background: null
  background_html: null
  background_aside: null
  background_bar: null
  background_div: null
  background_header: null
  text: null
